baseurl: /php-the-right-way
highlighter: rouge
markdown: kramdown
permalink: date
maruku:
    use_tex:    false
    use_divs:   false
    png_engine: blahtex
    png_dir:    images/latex
    png_url:    /images/latex

plugins:
    - jekyll-sitemap

defaults:
    -
      scope:
          path: ""
      values:
          sitemap: false
          image:
            path: /images/og-image.png
            width: 1024
            height: 640
            alt: "PHP - aber richtig."

# Excludes should be appended to the default
# https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml#L37-L55
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - Gruntfile.js
   - node_modules/
   - package.json
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - CNAME
   - CONTRIBUTING.md
   - LICENSE
   - README.md
   - pages/example.md

future: true

title: "PHP - aber richtig."
tagline: Referenz für PHP best Practices
description: Eine leicht verständliche Kurzreferenz für bewährte PHP-Herangehensweisen, anerkannte Coding-Standards und Links zu maßgeblichen Tutorials im Internet.
logo: /images/og-image.png
